# Generated by Django 4.1.2 on 2022-10-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='fecha_nacimiento',
            new_name='fecha_inicio_curso',
        ),
    ]
